apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-example
  labels:
    app: k8s-example
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-example
      tier: backend
  template:
    metadata:
      labels:
        app: k8s-example
        tier: backend
    spec:
      containers:
      - name: k8s-example
        image: lusyoe/k8s-example
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-example
  labels:
    app: k8s-example
    tier: backend
spec:
  selector:
    app: k8s-example
    tier: backend
  ports:
  - port: 8080
    name: k8s-backend

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-example
spec:
  rules:
  - host: k8s-example.com
    http:
      paths:
      - backend:
          serviceName: k8s-example
          servicePort: k8s-backend


